## Configuration for the training, evaluation
samples:
  - name: ME
    label: 1
    path: 0
    xsec: 1
    ngen: 1
  - name: FN
    label: 0
    path: 0
    xsec: 1
    ngen: 1
format:
    channel: 96
training:
    randomSeed1: 12345
    nDataLoaders: 4
    #nDataLoaders: 0
    splitFractions: [0.75, 0.25] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
