## Configuration for the training, evaluation
samples:
  - name: ME
    label: 1
    path: 
    xsec: 1
    ngen: 1
  - name: FN
    label: 0
    path: 
    xsec: 1
    ngen: 1
format:
    channel: 96
training:
    randomSeed1: 12345
    nDataLoaders: 0
    #nDataLoaders: 0
    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
